projects:
  noteapp:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: rzokfxqrejdbrelk5ygd2imib4
      endpoints:
        prod: >-
          https://nrv5jcdclnf7jg3gx2pqnogbii.appsync-api.us-east-2.amazonaws.com/graphql
